### PR TITLE
Update unlock_indicator.c

### PR DESCRIPTION
**Pull request by vistamon82**
Changed line 204 
text = "verifying…";

to

text = "verifying...";

Unicode ellipsis shows up as a blank box, so changed to 3 periods.

### CODE REVIEW

**Comment by Airblader** [comment]
As someone who actually cares about proper typography, seeing this PR hurts me, but ultimately I guess I have to agree. I'll just look the other way. :)

**Comment by stapelberg** [comment]
> Unicode ellipsis sometimes shows up as a blank box, so changed to 3 periods.

Can you be more specific about what “sometimes” means? Could it be that we need to be more picky about which font we request from the system? Like @Airblader, I’m inclined to fix this the proper way :).

**Comment by threefanger** [comment]
@Airblader @stapelberg I found that you had to have ttf-ms-fonts installed for the blank box to not show up.

@stapelberg i meant all the time, without the proper font.

**Comment by stapelberg** [comment]
From http://sources.debian.net/src/cairo/1.14.0-2.1/src/cairo.c/?hl=2720#L2708:

```
 * If text is drawn without a call to cairo_select_font_face(), (nor
 * cairo_set_font_face() nor cairo_set_scaled_font()), the default
 * family is platform-specific, but is essentially "sans-serif".
```

I think there are two ways to go about this issue:

1. Find out why your distribution ships with a default font that does not contain the unicode glyph “…” and convince your distribution to ship a better one.
2. Make i3lock specifically request a widely-available font which contains the unicode glyph “…”.

**Pull request closed without merging**
