### PR TITLE
includes a flag -g for blurring a screenshot of your desktop, used al…

### PR DESCRIPTION
**Pull request by lvitals**
…one this will attempt to capture the entire screen contents and blur it. however, this may also be used in conjunction with both a loaded image file and the tiling option

### CODE REVIEW

**Comment by Airblader** [comment]
We don't want this kind of feature in i3lock because we want to keep it simple and easy to avoid security issues, so unfortunately I'll have to reject and close this PR. There's been many pull requests for the same and similar features where we explain this in more detail. We think this kind of processing is best placed outside of i3 with dedicated graphics software.

**Comment by lvitals** [comment]
I understand this concern, like this kind of minimalist approach, but it is an improvisation using an external software for this, shell script is an improvisation not a solution. It is not a simple effect , UX Design is also necessary.

**Comment by Airblader** [comment]
i3lock doesn't try to be fancy in any way. If you want a fancy-looking lock screen you may want to use something else. I also think that using something like imagemagick for this perfectly fits the UNIX philosophy.

**Comment by lvitals** [comment]
i3lock has its fancy effects. It's a different screen lock of others. Unix philosophy is very good, small is beautiful, make each program do one thing well. But i3lock has other flags , eg "-i -c -b" native expanding its functionality , the blur effect is no different. I applied this functionality because I wanted my file ".i3/config" cleaner without many scripts.

**Comment by Airblader** [comment]
We generally have some features that we regret having added. But we care about compatibility and cannot remove them now. That's also why we're careful with introducing new features. 

You can keep your config small by putting the command chain into a script. There's really nothing wrong with that and it's certainly no reason to bloat i3lock. You want this flag, I want others and somebody else yet another thing. That's feature creep.

**Pull request closed without merging**
