### PR TITLE
control socket,lock image,udev-rules,systemd service

### PR DESCRIPTION
**Pull request by 0xbad0c0d3**

### CODE REVIEW

**Comment by stapelberg** [comment]
Can you please split this up into individual pull requests for each feature?

**Comment by 0xbad0c0d3** [comment]
No, i can't (( Only if it is posible to make pull request from bitbucket.org...

**Comment by Airblader** [comment]
There is a whole lot wrong with this PR. You replaced the versioning with hardcoded versions, checked in a lock picture, …

**Comment by 0xbad0c0d3** [comment]
(c) only for photo, it's my own photo. It's need write like this: "(c) Photo by ...."?

**Comment by Airblader** [comment]
Why is it in this PR at all?

**Comment by 0xbad0c0d3** [comment]
Becouse it's my first pull request and i don't know, that it shold be splited

**Comment by 0xbad0c0d3** [comment]
i can remove it, and commit only changed code of i3lock.c

**Comment by Airblader** [comment]
The pull request should only contain changes that should be merged into the main project that everyone will be using. It should *not* contain your personal modifications that are specific to you.

What Michael asked you to do is to split the PR into several pull requests as it consists of multiple, disjunct features that should be looked at, judged and merged individually.

**Comment by 0xbad0c0d3** [comment]
so? I shold close this PR, commit only i3lock.c and open new PR?

**Comment by Airblader** [comment]
You will have to do more than just i3lock.c. Of course you also need to add the documentation and all that. Again, the PR should consist of what you want to be merged into the project for everyone. Which means the changes need to be clean.

Closing this PR and sending a new one (well, new one**s**) is one option. You can also force push onto the same branch to update the PR.

You can also see from the failing Travis build that your formatting is incorrect.

**Comment by 0xbad0c0d3** [comment]
I can't understand why it's failed... my cairo.h version and ubuntu versions is equal, function declarations to...
travis build:
i3lock.c:1131:13: warning: implicit declaration of function ‘cairo_surface_set_device_scale’ [-Wimplicit-function-declaration]
gcc  -o i3lock i3lock.o unlock_indicator.o xcb.o xinerama.o -L/usr/local/lib -lcairo -lxcb-dpms -lxcb-xinerama -lxcb-util -lxcb-image -lxcb-shm -lxcb-xkb -lxcb -lxkbcommon-x11 -lxkbcommon   -lpam -lev -lm -lutil
i3lock.o: In function `main':
i3lock.c:(.text+0x2714): undefined reference to `cairo_surface_set_device_scale'
my build:
cc -std=c99 -pipe -Wall -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16  -D_GNU_SOURCE -DVERSION=\""2.7 (2015-07-20) With Control Socket"\"  -c -o xinerama.o xinerama.c
cc -std=c99 -pipe -Wall -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16  -D_GNU_SOURCE -DVERSION=\""2.7 (2015-07-20) With Control Socket"\"  -c -o xcb.o xcb.c
cc -std=c99 -pipe -Wall -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16  -D_GNU_SOURCE -DVERSION=\""2.7 (2015-07-20) With Control Socket"\"  -c -o i3lock.o i3lock.c
cc -std=c99 -pipe -Wall -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16  -D_GNU_SOURCE -DVERSION=\""2.7 (2015-07-20) With Control Socket"\"  -c -o unlock_indicator.o unlock_indicator.c
cc  -o i3lock xinerama.o xcb.o i3lock.o unlock_indicator.o -lcairo -lxcb-dpms -lxcb-xinerama -lxcb-util -lxcb-image -lxcb-shm -lxcb-xkb -lxcb -lxkbcommon-x11 -lxkbcommon  -lpam -lev -lm -lutil

**Comment by Airblader** [comment]
It fails because your formatting is incorrect. The Travis build does more than just run "make". You need to run clang-format on the changed files.

**Comment by 0xbad0c0d3** [comment]
Ok, now it's clang formatted, it's fail becouse something wrong with libs...
i3lock.c:(.text+0x2714): undefined reference to `cairo_surface_set_device_scale'
but libcairo2-dev and ArchLinux cairo equals...

**Comment by Airblader** [comment]
Have you verified that this function is available in the cairo version that we use? Maybe it was added later on.

**Comment by 0xbad0c0d3** [comment]
Which version do you use?

**Comment by Airblader** [comment]
Travis runs on Ubuntu 12.04 and according to [this](http://packages.ubuntu.com/precise/libcairo2-dev), this gives us `libcairo2-dev (1.10.2-6.1ubuntu2)`

**Comment by 0xbad0c0d3** [comment]
My version 1.14.2-1

**Comment by Airblader** [comment]
According to the cairo changelog, `cairo_surface_set_device_scale` was introduced with 1.14.0 (2014-10-13).

**Comment by 0xbad0c0d3** [comment]
So? Should i do anything else?

**Comment by Airblader** [comment]
Yes, what Michael said in the beginning:

> Can you please split this up into individual pull requests for each feature?

Also please note that Michael is the person deciding whether this gets merged at all.

**Comment by 0xbad0c0d3** [comment]
Ok.
21 июля 2015 г. 19:17 пользователь "Ingo Bürk" <notifications@github.com>
написал:

**Pull request closed without merging**
