### PR TITLE
Switch to autotools

### PR DESCRIPTION
**Pull request by stapelberg**
This was largely copied from the i3 configure.ac and Makefile.am.

cc @jasperla @kaashif — I haven’t tested this on non-Linux, so if you could test this, that’d be appreciated.

### CODE REVIEW

**Comment by Airblader** [comment]
Obviously not going to review all the details of this. :-)

**Comment by stapelberg** [comment]
I’m going to go ahead and merge this. Feedback for non-linux still very welcome, but now in form of a pull request please :).

**Comment by jasperla** [comment]
This mostly looks fine on OpenBSD, except for two small issues:
- it explicitly checks for `iconv_open()` which fails. it seems there is [upstream documentation](https://www.gnu.org/software/gettext/manual/html_node/AM_005fICONV.html) on the topic. Perhaps i3lock (and i3 too for that matter) should use the more portable approach of `AM_ICONV()`?
- pam is unconditionally linked in (pull request forth-coming)

**Comment by stapelberg** [comment]
Thanks for looking. Pull requests for both issues welcome :)

**Pull request merged**
