### PR TITLE
Add option to disable the state messages

### PR DESCRIPTION
**Pull request by johrpan**
... for those who don't like them.

### CODE REVIEW

**Comment by Airblader** [comment]
I'll leave it to @stapelberg to decide about merging this at all, but if we do, I'd personally vote against `-s`. Not every option needs a single-letter alias and IMHO they should only be used for options that are intuitively clear. Worst case we end up with something much more fit for `-s` but then it's already used for this (very minor) change.

**Comment by stapelberg** [comment]
Please just use `--no-unlock-indicator` instead. We don’t want to add hundreds of options to i3lock to make every little detail of it configurable.

**Comment by Airblader** [comment]
Same time. :-)

**Comment by johrpan** [comment]
Ok, no problem, luckily this is so small that I can just patch it for my own machine, but I thought there where others who would like to use this.

**Pull request closed without merging**
